# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# azv.py
# Created on: 2022-07-26 09:20:36.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
u_geom_1_salida = "u_geom_1_salida"
u_geom_1_salida__3_ = u_geom_1_salida

# Process: Calculate Field
arcpy.CalculateField_management(u_geom_1_salida, "azv1", "clas( !azv! )", "PYTHON_9.3", "def clas(azv):\\n if azv ==\"ALTO \":\\n  return 1\\n elif azv ==\"MEDIO\":\\n  return 2\\n elif azv ==\"BAJO\":\\n  return 3\\n elif azv ==\"NULO\":\\n  return 4\\n elif azv ==\"NO APLICA\":\\n  return 998")

