# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# calculate field.py
# Created on: 2022-07-12 08:09:41.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
u_geom_9c = "u_geom_9c"
u_geom_9c__2_ = u_geom_9c

# Process: Calculate Field
arcpy.CalculateField_management(u_geom_9c, "prueba", "[ptero]", "VB", "")

