# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# fci.py
# Created on: 2022-07-26 09:27:39.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
u_geom_1_salida = "u_geom_1_salida"
u_geom_1_salida__3_ = u_geom_1_salida

# Process: Calculate Field
arcpy.CalculateField_management(u_geom_1_salida, "fci1", "clas( !fci! )", "PYTHON_9.3", "def clas(fci):\\n if fci ==\"AGUDA\":\\n  return 1\\n elif fci ==\"REDONDEADA\":\\n  return 2\\n elif fci ==\"PLANA\":\\n  return 3\\n elif fci ==\"MIXTA\":\\n  return 4\\n elif fci ==\"NO APLICA\":\\n  return 998")

