# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# fve.py
# Created on: 2022-07-26 09:30:05.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
u_geom_1_salida = "u_geom_1_salida"
u_geom_1_salida__2_ = u_geom_1_salida

# Process: Calculate Field
arcpy.CalculateField_management(u_geom_1_salida, "fci1", "clas( !fve! )", "PYTHON_9.3", "def clas(fve):\\n if fve ==\"CONCAVA\":\\n  return 1\\n elif fve ==\"CONVEXA\":\\n  return 2\\n elif fve ==\"RECTILINEA\":\\n  return 3\\n elif fve ==\"IRREGULAR\":\\n  return 4\\n elif fve ==\"MIXTA\":\\n  return 5\\n elif fve ==\"NO APLICA\":\\n  return 998\\n")

