# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# revisar_cortes.py
# Created on: 2022-04-19 10:22:10.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy, os

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")


# Local variables:
ENTREGA_2 = "D:\\Poblados\\ENTREGA_2"
v1 = ENTREGA_2
Fuente = "D:\\Poblados\\entrega\\Fuente.shp"
I_Fuente_Nombre = Fuente
Value = "1"
poblados_p = "poblados_p"
poblados_p_Clip = "C:\\Users\\salgado_maria\\Documents\\ArcGIS\\Default.gdb\\poblados_p_Clip"

# Process: Iterate Feature Selection
arcpy.IterateFeatureSelection_mb(Fuente, "Nombre #", "false")

# Process: Create Folder
arcpy.CreateFolder_management(ENTREGA_2, Value)
j =arcpy.os.join(ENTREGA_2,Value,"poblado_p")
print j
# Process: Clip
arcpy.Clip_analysis(poblados_p, I_Fuente_Nombre, j, "")

