# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# rpdt.py
# Created on: 2022-07-26 09:33:55.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
u_geom_1_salida = "u_geom_1_salida"
u_geom_1_salida__3_ = u_geom_1_salida

# Process: Calculate Field
arcpy.CalculateField_management(u_geom_1_salida, "fci1", "clas( !rpdt! )", "PYTHON_9.3", "def clas(rpdt):\\n if rpdt ==\"0 - 2 %\":\\n  return 1\\n elif rpdt ==\"> 2 - 5 %\":\\n  return 2\\n elif rpdt ==\"> 5 - 12 %\":\\n  return 3\\n elif rpdt ==\"> 12 - 25 %\":\\n  return 4\\n elif rpdt ==\"> 25 - 40 %\":\\n  return 5\\n elif rpdt ==\"> 40 - 70 %\":\\n  return 6\\n elif rpdt ==\"> 70 - 100 %\":\\n  return 7\\n elif rpdt ==\"> 100 - 150 %\":\\n  return 8\\n elif rpdt ==\"> 150 - 200 %\":\\n  return 9\\n elif rpdt ==\"> 200 %\":\\n  return 10\\n elif rpdt ==\"NO APLICA\":\\n  return 998")

