# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# rpdt_desc.py
# Created on: 2022-07-26 09:37:19.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
u_geom_1_salida = "u_geom_1_salida"
u_geom_1_salida__2_ = u_geom_1_salida

# Process: Calculate Field
arcpy.CalculateField_management(u_geom_1_salida, "rpdt_desc1", "clas( !rpdt_desc! )", "PYTHON_9.3", "def clas(rpdt):\\n if rpdt ==\"PLANA\":\\n  return 1\\n elif rpdt ==\"MUY SUAVE\":\\n  return 2\\n elif rpdt ==\"SUAVE\":\\n  return 3\\n elif rpdt ==\"MEDIA\":\\n  return 4\\n elif rpdt ==\"MEDIA A FUERTE\":\\n  return 5\\n elif rpdt ==\"FUERTE\":\\n  return 6\\n elif rpdt ==\"MUY FUERTE\":\\n  return 7\\n elif rpdt ==\"ESCARPADA\":\\n  return 8\\n elif rpdt ==\"MUY ESCARPADA\":\\n  return 9\\n elif rpdt ==\"ABRUPTA\":\\n  return 10\\n elif rpdt ==\"NO APLICA\":\\n  return 998")

