import arcpy
arcpy.env.overwriteOutput = True

capa = GDB = arcpy.GetParameterAsText(0)
capa=arcpy.SearchCursor(capa)
for i in capa:
      arcpy.AddMessage("                </sld:Rule>")
      arcpy.AddMessage("                <sld:Rule>")
      arcpy.AddMessage("                    <sld:Name>"+i.getValue("CBT_1")+"</sld:Name>")
      arcpy.AddMessage("                    <sld:Title>"+i.getValue("CBT_1")+"</sld:Title>")
      arcpy.AddMessage("                    <ogc:Filter>")
      arcpy.AddMessage("                        <ogc:PropertyIsEqualTo>")
      arcpy.AddMessage("                            <ogc:PropertyName>cbt</ogc:PropertyName>")
      arcpy.AddMessage("                            <ogc:Literal>"+i.getValue("CBT_1")+"</ogc:Literal>")
      arcpy.AddMessage("                        </ogc:PropertyIsEqualTo>")
      arcpy.AddMessage("                    </ogc:Filter>")
      arcpy.AddMessage("                    <sld:MaxScaleDenominator>4500000</sld:MaxScaleDenominator>")
      arcpy.AddMessage("                    <sld:PolygonSymbolizer>")
      arcpy.AddMessage("                        <sld:Fill>")
      arcpy.AddMessage("                            <sld:GraphicFill>")
      arcpy.AddMessage("                                <sld:Graphic>")
      arcpy.AddMessage("                                    <sld:ExternalGraphic>")
      arcpy.AddMessage(i.getValue("SIMBOLOGIA"))
      arcpy.AddMessage("                                        <sld:Format>image/png</sld:Format>")
      arcpy.AddMessage("                                    </sld:ExternalGraphic>")
      arcpy.AddMessage("                                    <sld:Opacity>")
      arcpy.AddMessage("                                        <ogc:Literal>0.8</ogc:Literal>")
      arcpy.AddMessage("                                    </sld:Opacity>")
      arcpy.AddMessage("                                    <sld:Size>")
      arcpy.AddMessage("                                        <ogc:Literal>60.0</ogc:Literal>")
      arcpy.AddMessage("                                    </sld:Size>")
      arcpy.AddMessage("                                    <sld:Rotation>")
      arcpy.AddMessage("                                        <ogc:Literal>0.0</ogc:Literal>")
      arcpy.AddMessage("                                    </sld:Rotation>")
      arcpy.AddMessage("                                </sld:Graphic>")
      arcpy.AddMessage("                            </sld:GraphicFill>")
      arcpy.AddMessage("                            <sld:CssParameter name='fill'>")
      arcpy.AddMessage(i.getValue("OGC"))
      arcpy.AddMessage("                            </sld:CssParameter>")
      arcpy.AddMessage("                            <sld:CssParameter name='fill-opacity'>")
      arcpy.AddMessage("                                <ogc:Literal>0.8</ogc:Literal>")
      arcpy.AddMessage("                            </sld:CssParameter>")
      arcpy.AddMessage("                        </sld:Fill>")
      arcpy.AddMessage("                    </sld:PolygonSymbolizer>")
